### ISSUE TITLE
Rank synonyms by frequency in autocomplete

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#134]
@divya-gopinath do we have frequency data for synonyms?

**Comment by divya-gopinath** [comment]
For symptom autocomplete, the order of the synonyms is from most frequent to least frequent. Will change the HPI autocomplete ontology to reflect that

**Comment by lukesmurray** [comment]
ok so the synonyms are pushed in the order they appear in the csv. let me know when the ontology is updated in the data folder and i will close this.

https://github.com/lukesmurray/bidmc-ml-ui/blob/ad12d92edd893389518cde5c3b106a3fc7258e62/src/components/suggestionHooks.ts#L41-L50

**Comment by divya-gopinath** [comment]
ontology is updated, feel free to close.
