### ISSUE TITLE
Make space the autocomplete trigger

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#135]
we may want to only show autocomplete if we have a certain threshold of certainty that the user wants to see the autocomplete. A simple first heuristic for this is after `n` characters. but this could be an ML problem.

**Comment by lukesmurray** [comment]
Started work on this in  97fc891.

Some issues we are going to run into.

- performance degrades since almost everything is a potential autocomplete
  - this is very noticeable if you mash the backspace button
- we sometimes allow for autocomplete after special characters i.e. `(, +` we should parameterize these since when we add suggestions we need to take into account that we are using `(` or `+` as a trigger instead of a space. Try typing `(htn` and hitting enter. The opening parentheses will disappear since `addSuggestion` assumes the fist char is the trigger

**Comment by lukesmurray** [comment]
Suggestions store currently has `/` hardcoded. Needs to be parameterized. Also Steve wants space and `/` as triggers. We may be able to use multiple decorator strategies or something...

**Comment by divya-gopinath** [comment]
Closing because we now have prompted autocomplete.
