### ISSUE TITLE
Autofacet the Autocomplete

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#142]
If the user types `h/o` they most likely want to insert HPI autocompletions so we should autofill `/h ` which triggers a dropdown for HPI autocompletions.

All documented rules

- `h/o` (history of) triggers HPI filter
- `c/o` (complains of) triggers symptoms filter
- `s/p` (status post) triggers an hpi filter
- `p/w` (presents with) triggers an hpi filter (@lukesmurray do you mean for this to say symptom filter? because usually it'll be p/w [cold, fever] etc.) 

eventually we should learn these things.

**Comment by divya-gopinath** [comment]
Closed because we now have contextual triggers rather than auto-adding autocomplete keywords.
