### ISSUE TITLE
Add a help button which contains a short tutorial

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#145]
At the very least we want keyboard shortcuts for autocomplete.

**Comment by lukesmurray** [comment]
Things to mention in the tutorial

- autofaceting
- shortcuts from #142 

Suggestion prefixes from https://github.com/lukesmurray/bidmc-ml-ui/blob/9f800a47d6168fd9393f362a8e80bb16eee4ddb3/src/components/SuggestionSection.tsx#L157-L167

**Comment by divya-gopinath** [comment]
Closing as per https://github.com/lukesmurray/bidmc-ml-ui/commit/3fd5634eca5cf4ad881fe9bf4a6a2fe0394aebdf
