### ISSUE TITLE
Copy and paste chips not supported on IE11/Edge

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#149]
I defer copy and pasting and chips to a library because its a surprisingly annoying thing to implement. Relevant non support mentioned [here](https://github.com/thibaudcolas/draftjs-conductor/blob/0cac2220a5f6537e27c2fd01e2c7d397f5c25b36/README.md)

Relevant complicated discussion [here](https://github.com/facebook/draft-js/issues/787)

**Comment by divya-gopinath** [comment]
Working on IE11/Edge for me.
