### ISSUE TITLE
s/p can go off the trigger

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#157]
most of the time it is status post and a current thing not a past thing.

s/p can mean past procedure or after a current event like s/p fall etc...

**Comment by divya-gopinath** [comment]
s/p should prob default to symptom autocomplete

**Comment by lukesmurray** [comment]
I made scoping accept arrays and `s/p` creates the ordered scope [SYMPTOM, HPI]
