### ISSUE TITLE
post suggestion autoscope interaction

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#182]
![diabetes_bug](https://user-images.githubusercontent.com/34020210/76549911-9b694d00-6467-11ea-89d1-da5daa4754b7.gif)

post suggestions interrupt multi word auto scope

**Comment by divya-gopinath** [comment]
I don't know if there's an elegant solution to this. One thing is to potentially find out what concepts are proper substrings of other concepts, and then figure out what behavior we want. For example, maybe for diabetes, we don't post correct until we are X tokens away.

**Comment by lukesmurray** [comment]
this is now fixed by greedy prefix matching using a trie and keeping track of start and end of match.
