### ISSUE TITLE
Continuation Tokens should be able to remap scope

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#223]
Currently continuation tokens just continue the previous scope. This works well for phrases such as `hypertension and diabetes` but does not make sense with phrases like `coumadin for afib` or `afib on coumadin`. In the case `coumadin for afib` we want to attach a remapping on the continuation `for` from `MED => HPI`. With `afib on coumadin` we want to attach a remapping for the continuation `on` from `PROBLEM => MED`. 

A similar logic could be applied to trigger phrases. `Treated w/` should map to `MED` and `Treated for` should map to `HPI`. For trigger phrases its not completely clear where we want the mapping to be. It could be on the trigger or on the continuation token. TBD.

**Comment by divya-gopinath** [comment]
Addressed via learned triggers as per https://github.com/lukesmurray/bidmc-ml-ui/commit/5cd509500be4da4cd9b6ba075700512fcc403116
